DATA work.BONE;

  INFILE "/folders/myfolders/data/T3_6_BONE.dat";
  INPUT OBS Y1 Y2 Y3 Y4;

TITLE "HW6 Q-13.8 (a)";


LABEL Y1='8 yr' Y2='8 1/2 yr' Y3='9 yr' Y4='9 1/2 yr';

PROC FACTOR METHOD=PRIN NFACT=2 ROTATE=VARIMAX PLOT = ALL;
VAR Y1-Y4;
RUN;

PROC FACTOR METHOD=PRIN NFACT=2 ROTATE=HK PLOT = ALL;
VAR Y1-Y4;
RUN;