DATA work.PILOT;

  INFILE "/folders/myfolders/data/T5_6_PILOT.dat";
  INPUT OBS X1 X2 X3 X4 X5 X6;

TITLE "HW6 Q-13.12";


PROC FACTOR METHOD=PRIN NFACT=3 ROTATE=VARIMAX PLOT = ALL;
VAR X1-X6;

RUN;

PROC FACTOR METHOD=PRIN PRIORS=SMC NFACT=3 ROTATE=VARIMAX PLOT = ALL;
VAR X1-X6;
RUN;