DATA work.FISH;

  INFILE "/folders/myfolders/data/T6_17_FISH.dat";
  INPUT METHOD AROMA FLAVOR TEXTURE MOISTURE;
RUN;

TITLE "HW5 Q-8.11";

PROC FORMAT;
  VALUE METHOD 1='METHOD 1' 2='METHOD 2' 3='METHOD 3';
RUN;

PROC CANDISC OUT=CAND;
  CLASS METHOD;
RUN;

PROC PRINT DATA=CAND;
RUN;

PROC PLOT DATA=CAND;
  PLOT CAN2*CAN1=METHOD;
RUN;
