DATA work.SNAPBEAN;
  
  INFILE "/folders/myfolders/data/T6_18_SNAPBEAN.dat";
  INPUT SOWING VARIETY SNAPBEAN YIELD SLA TOTALYIELD AVGSLA;

TITLE "HW3 Q-6.28 a)";

PROC GLM;
  CLASS SOWING VARIETY;
  MODEL YIELD SLA TOTALYIELD AVGSLA = SOWING VARIETY SOWING*VARIETY;
  MANOVA H=_ALL_/PRINTH PRINTE MSTAT=EXACT;
RUN;
