DATA work.DIABETES;

  INFILE "/folders/myfolders/data/T3_4_DIABETES.dat";
  INPUT NUM Y1 Y2 X1 X2 X3;

TITLE "HW4 Q-10.14";

PROC REG;
  MODEL Y1 Y2 = X1 X2 X3;
  OVERALL: MTEST /PRINT CANPRINT MSTAT = EXACT;
  PARTIAL_X1: MTEST X1/PRINT CANPRINT MSTAT = EXACT;
  PARTIAL_X2: MTEST X2/PRINT CANPRINT MSTAT = EXACT;
  PARTIAL_X3: MTEST X3/PRINT CANPRINT MSTAT = EXACT;
RUN;
